stages:
  - build
  - store

build-gerbers:
  stage: build
  image:
    name: kicad/kicad:nightly
    pull_policy: if-not-present
  script:
    - mkdir -p build/src
    - cp elec/layout/bike_light.kicad_pcb build/src/
    - sed -i "s/"'{{GITHASH}}'"/$CI_COMMIT_SHORT_SHA/g" build/src/bike_light.kicad_pcb
    - mkdir -p build/gerbers
    - kicad-cli pcb export gerbers -o build/gerbers/ build/src/bike_light.kicad_pcb
    - kicad-cli pcb export drill -o build/gerbers/ build/src/bike_light.kicad_pcb
    - zip "build/gerbers-$CI_COMMIT_SHORT_SHA.zip" build/gerbers/*

    # position files need some massaging for JLCPCB
    - kicad-cli pcb export pos --format csv --units mm --use-drill-file-origin -o build/bike_light-pos.csv build/src/bike_light.kicad_pcb
    - POS_HEADER="$(cat metadata/pos-header)"
    - sed -i "1s/.*/$POS_HEADER/" build/bike_light-pos.csv
  artifacts:
    paths:
      - build/

build-bom:
  stage: build
  image: registry.atopile.io/atopile/atopile:latest
  script:
    - ato build --target "bom-jlcpcb" elec/src
  artifacts:
    paths:
      - build/

store-build:
  stage: store
  image: alpine
  script:
    - echo "noop"
  artifacts:
    paths:
      - build/
